#!perl

# FRAGMENT id=shcompgen-hint command=cryp-exchange

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;
use Log::ger;

use Perinci::CmdLine::cryp;

my $prefix = "/App/cryp/exchange/";

Perinci::CmdLine::cryp->new(
    url => $prefix,
    log => 1,
    pass_cmdline_object => 1,
    config_filename => ["cryp.conf", "cryp-exchange.conf"],
    subcommands => {
        # public
        "ls-accounts"       => { url => "${prefix}list_accounts", },
        "ls-exchanges"      => { url => "${prefix}list_exchanges", },
        "ls-pairs"          => { url => "${prefix}list_pairs", },

        # private
        "get-order-book"    => { url => "${prefix}get_order_book", },
        "ls-balances"       => { url => "${prefix}list_balances", },
    },
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

Create configuration in F<~/.config/cryp-exchange.conf> (or
F<~/.config/cryp.conf> so configuration can be shared with the other C<cryp-*>
family of scripts):

 [exchange/bitcoin-indonesia]
 api_key    = S6WBYR6Q-TVMTSFOA-YWK6GSNT-H0JMEK6Z-YDF5ML9Y
 api_secret = e16064aa7fb477b267fe774df62194f33583c7f46a09ad931ca2e097aeaa9c9296e1c3b2734bab71

 ; if you have another account on the same exchange
 [exchange/bitcoin-indonesia/wifey]
 api_key    = EKSGJUOR-ROR9K24P-Q45UBWVG-GZHANPQV-UY4Z1WBM
 api_secret = 71100dc13ffe4d082239c06b5c36fd8f0548cd97056ffa2ee491ae4dfd4f996fb468ef3c70b12073

 [exchange/gdax]
 api_key        = 2171d01f1de2518c94a11870a6df22d0
 api_secret     = 9B8T2nPFMRUiUIKA82txjaO09iNnJXBMVMdkDgJ0i2YambYKQY8DZAS54ERZE0sE2lzYrpTWfpU7/110xfesZluY
 api_passphrase = gdllszgwO774NN

To list supported exchanges:

 % cryp-exchange ls-exchanges
 % cryp-exchange ls-exchanges -l

To list pairs offered in an exchange:

 % cryp-exchange ls-pairs bitcoin-indonesia
 % cryp-exchange ls-pairs gdax -l

To list accounts:

 % cryp-exchange ls-accounts
 % cryp-exchange ls-accounts -l
 % cryp-exchange ls-accounts -I gdax -l ;# only accounts on gdax
 % cryp-exchange ls-accounts -X gdax -l ;# all accounts except those on gdax

To get order book:

 % cryp-exchange get-order-book gdax


=head1 DESCRIPTION

B<Early release. More functionality will be added in the future.>

This utility (and the corresponding backend modules) provide a common interface
to interact with various cryptocurrency exchanges: common set of subcommands
(methods) with common arguments and result format, standardized currency codes
(following L<CryptoCurrency::Catalog>) and pair formats (e.g. C<BTC/USD>).


=head1 SEE ALSO

The other C<cryp-*> scripts in the family.
